---
{{- if .Values.rbac.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-server-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alert-manager-account
  namespace: {{ .Release.Namespace }}
---
{{- end }}
