---
{{- if .Values.kubernetes.rbac }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prometheus-clusterrolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: prometheus-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: prometheus-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
